name: signup_ui
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+4
  provider: ^4.0.4
  google_maps_flutter:  
  font_awesome_flutter: ^8.2.0
  url_launcher: ^5.4.0  
  google_static_maps_controller: ^0.4.1
    

  
  cupertino_icons: ^0.1.3
  flutter_svg: ^0.20.0-nullsafety.3
  google_sign_in: "^4.5.4"
  flutter_signin_button: ^1.0.0
  flutter_uploader: ^1.2.0
  cloud_firestore: 
  firebase_storage:
  image_picker:
  transparent_image:
  curved_navigation_bar:
  multi_image_picker:
  firebase_auth: ^0.18.1
  firebase_core : ^0.5.0
  geolocator: ^6.0.0+4
  intl:
  date_format:
  dropdown_formfield: ^0.1.3
  geocoding: 
  permission_handler: ^5.0.1+1 
  fluttertoast: ^7.1.4
  geocoder: ^0.2.1
  google_fonts:
    
dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - asset/img/
  